services:
  proxy:
    build:
      context: ./proxy
    environment:
      MODE: ${MODE:-remote}
      SERVER_NAME: ${SERVER_NAME:-geodock.intra}
      UPSTREAM_BAN: ${UPSTREAM_BAN:-https://api-adresse.data.gouv.fr}
      UPSTREAM_HOST: ${UPSTREAM_HOST:-api-adresse.data.gouv.fr}
      LOCAL_UPSTREAM: ${LOCAL_UPSTREAM:-http://geocoder-api:3000}
      UPSTREAM_SSL_PROTOCOLS: ${UPSTREAM_SSL_PROTOCOLS:-TLSv1.3}
      FALLBACK_ON_404: ${FALLBACK_ON_404:-false}
      SSL_PROTOCOLS: ${SSL_PROTOCOLS:-TLSv1.2 TLSv1.3}
      REDIRECT_HTTP_TO_HTTPS: ${REDIRECT_HTTP_TO_HTTPS:-false}
      EXPOSE_HEALTH_ON_HTTP: ${EXPOSE_HEALTH_ON_HTTP:-true}
    ports:
      - "${HOST_PORT_HTTP:-80}:80"
      - "${HOST_PORT_HTTPS:-443}:443"
    volumes:
      - type: bind
        source: ./proxy/certs
        target: /etc/nginx/certs
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/80 && printf \"GET /_health HTTP/1.0\\r\\n\\r\\n\" >&3 && head -n1 <&3 | grep -q 200'"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks: [geodock]

networks:
  geodock:
    driver: bridge
